name: Deploy signaling server

on:
  push:
    branches: [main]
    paths:
      - val-town/main.ts

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install vt
        run: deno install -grAf jsr:@valtown/vt

      - name: Push to Val Town
        working-directory: val-town
        env:
          VAL_TOWN_API_KEY: ${{ secrets.VAL_TOWN_API_KEY }}
        run: vt push
